export const responses = {
  successCreateProject: "Adding new project was successful",
  successUpdateProject: "Updating project was successful",
  successDeleteProject: "Deleting project was successful",
  successGetProject: "Project has been found",
  errorNotFound: "Project not found",
  errorCreateProject: "An error occurred adding new project",
  errorUpdateProject: "An error occurred updating the project",
  errorDeleteProject: "An error occurred deleting the project",
  serverError: "A server error occurred",
  successSignUp: "Sign up was successful",
  successSignIn: "Sign in was successful",
  userIsExist: "User already exist",
  errorSignUp: "Invalid created new user",
  errorSignIn: "Invalid username or password",
  errorField: "Please recheck field!",
  errorUserNotFound: "User not found",
};
